### PR TITLE
Full refresh for Linux

### PR DESCRIPTION
**Pull request by xyproto**
* Correct typo in LICENSE filename
* Add dnload wrapper script
* Convert Python source code to Python 3
* Format all Python source code with AutoPEP8
* Rename "src" to "examples"
* Add "setup.py" for easy installation of the python module
* Fix exit syscall on Linux
* Fix shell decompression header (now works on Arch Linux)
* Modify defaults to not cause errors on Linux (tested on Arch)

The changes probably need to be tested on FreeBSD before merging.

The above changes has been tested in the [shrinky](https://aur.archlinux.org/packages/shrinky/) and [shrinky-intro](https://aur.archlinux.org/packages/shrinky-intro/) unofficial Arch Linux packages, but I would rather use dnload instead of a fork, if the proposed changes are accepted.

### CODE REVIEW

**Comment by xyproto** [comment]
* Also started the work with adding Vulkan support, but only one function has been added yet.

**Comment by xyproto** [comment]
Hang on, it's hard to compare the changes because of the autopep8 code formatting. I think perhaps the latest changes to dnload/master were lost in the merge.

I will create a separate pull request for only Python 2 -> Python 3 and for the autopep8 changes (if you are at all interested in any of these changes, that is).

**Comment by trilkk** [comment]
This looks awesome, and I am interested, but as things stand it's practically impossible to follow the changes due to the formatting and I'd be wary of merging 80 files worth of changes without being able to review them. I hope you can understand, but I really appreciate this work.

BTW: support for Python 2.7 has been intentional - the code has been written to work on 2.7 and 3.4+ both. I guess it's about time for 2.7 to disappear into history though.

Would it be possible to retain the 2 spaces formatting to discard most of the diff and get the actual content changes in a more readable format? If python standard heavily enforces 4 lines, that could be a whole another changeset in itself?

**Comment by xyproto** [comment]
I split this pull request into 3 other pull requests.

**Pull request closed without merging**
